{
 "title": "Report Feed Scraper",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last Scrape Attempt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - 36000 - max(report_feed_last_scrape_time)",
     "legendFormat": "last scrape"
    }
   ]
  },
  {
   "title": "Successful Feeds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(report_feed_last_scrape_time{status=\"successful\"}) by (publisher))",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Failed Feeds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(report_feed_last_scrape_time{status=\"failed\"}) by (publisher))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Daily Reports",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(report_feed_reports_total[1d]))",
     "legendFormat": "Total Reports"
    }
   ]
  },
  {
   "title": "Failed Scrapes",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "max(report_feed_last_scrape_time{status!=\"successful\"} * 1000) by (publisher, distribution)",
     "legendFormat": "publisher"
    }
   ]
  },
  {
   "title": "Successful Scrapes",
   "type": "table",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "max(report_feed_last_scrape_time{status=\"successful\"} * 1000) by (publisher, distribution)",
     "legendFormat": "publisher"
    }
   ]
  }
 ]
}